// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for About Us documents */
interface AboutUsDocumentData {
    /**
     * Title field in *About Us*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_us.title
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *About Us*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_us.description
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
}
/**
 * About Us document from Prismic
 *
 * - **API ID**: `about_us`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutUsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<AboutUsDocumentData>, "about_us", Lang>;
/** Content for Automation documents */
interface AutomationDocumentData {
    /**
     * Title field in *Automation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: automation.title
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *Automation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: automation.description
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
}
/**
 * Automation document from Prismic
 *
 * - **API ID**: `automation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AutomationDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<AutomationDocumentData>, "automation", Lang>;
/** Content for Contacts documents */
interface ContactsDocumentData {
    /**
     * Title field in *Contacts*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contacts.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Header field in *Contacts*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contacts.header
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    header: prismicT.KeyTextField;
    /**
     * Short Text field in *Contacts*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contacts.short_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    short_text: prismicT.KeyTextField;
    /**
     * Short Text 2 field in *Contacts*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contacts.short_text_2
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    short_text_2: prismicT.KeyTextField;
    /**
     * Map Link field in *Contacts*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contacts.map_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    map_link: prismicT.KeyTextField;
    /**
     * Header Img field in *Contacts*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: contacts.header_img
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    header_img: prismicT.ImageField<never>;
    /**
     * Slice Zone field in *Contacts*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: contacts.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<ContactsDocumentDataSlicesSlice>;
    /**
     * SEO Title field in *Contacts*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contacts.seo_title
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    seo_title: prismicT.KeyTextField;
    /**
     * SEO Description field in *Contacts*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contacts.seo_description
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    seo_description: prismicT.KeyTextField;
}
/**
 * Slice for *Contacts → Slice Zone*
 *
 */
type ContactsDocumentDataSlicesSlice = ContactListSlice;
/**
 * Contacts document from Prismic
 *
 * - **API ID**: `contacts`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ContactsDocumentData>, "contacts", Lang>;
/** Content for Designing documents */
interface DesigningDocumentData {
    /**
     * Title field in *Designing*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: designing.title
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *Designing*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: designing.description
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
}
/**
 * Designing document from Prismic
 *
 * - **API ID**: `designing`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DesigningDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<DesigningDocumentData>, "designing", Lang>;
/** Content for Footer documents */
interface FooterDocumentData {
    /**
     * Logo field in *Footer*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
    /**
     * VAT code field in *Footer*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.vat_code
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    vat_code: prismicT.KeyTextField;
    /**
     * Company Code field in *Footer*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.company_name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    company_name: prismicT.KeyTextField;
    /**
     * Privacy Link field in *Footer*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.privacy_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    privacy_link: prismicT.KeyTextField;
    /**
     * copyright field in *Footer*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.copyright
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    copyright: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Footer*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<FooterDocumentDataSlicesSlice>;
}
/**
 * Slice for *Footer → Slice Zone*
 *
 */
type FooterDocumentDataSlicesSlice = FooterLinksSlice;
/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<FooterDocumentData>, "footer", Lang>;
/** Content for Gallery documents */
interface GalleryDocumentData {
    /**
     * Title field in *Gallery*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: gallery.title
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *Gallery*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: gallery.description
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
}
/**
 * Gallery document from Prismic
 *
 * - **API ID**: `gallery`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GalleryDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<GalleryDocumentData>, "gallery", Lang>;
/** Content for Home documents */
interface HomeDocumentData {
    /**
     * Title field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.title
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.description
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
}
/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;
/** Content for Production documents */
interface ProductionDocumentData {
    /**
     * Title field in *Production*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: production.title
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *Production*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: production.description
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
}
/**
 * Production document from Prismic
 *
 * - **API ID**: `production`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductionDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ProductionDocumentData>, "production", Lang>;
/** Content for Repair documents */
interface RepairDocumentData {
    /**
     * Title field in *Repair*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: repair.title
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *Repair*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: repair.description
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
}
/**
 * Repair document from Prismic
 *
 * - **API ID**: `repair`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RepairDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<RepairDocumentData>, "repair", Lang>;
export type AllDocumentTypes = AboutUsDocument | AutomationDocument | ContactsDocument | DesigningDocument | FooterDocument | GalleryDocument | HomeDocument | ProductionDocument | RepairDocument;
/**
 * Primary content in ContactList → Primary
 *
 */
interface ContactListSliceDefaultPrimary {
    /**
     * Title field in *ContactList → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_list.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Link field in *ContactList → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_list.primary.link
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    link: prismicT.KeyTextField;
}
/**
 * Default variation for ContactList Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ContactList`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContactListSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ContactListSliceDefaultPrimary>, never>;
/**
 * Slice variation for *ContactList*
 *
 */
type ContactListSliceVariation = ContactListSliceDefault;
/**
 * ContactList Shared Slice
 *
 * - **API ID**: `contact_list`
 * - **Description**: `ContactList`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContactListSlice = prismicT.SharedSlice<"contact_list", ContactListSliceVariation>;
/**
 * Primary content in FooterLinks → Primary
 *
 */
interface FooterLinksSliceDefaultPrimary {
    /**
     * Title field in *FooterLinks → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_links.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
}
/**
 * Item in FooterLinks → Items
 *
 */
export interface FooterLinksSliceDefaultItem {
    /**
     * Name field in *FooterLinks → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_links.items[].name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Link field in *FooterLinks → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_links.items[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    link: prismicT.KeyTextField;
}
/**
 * Default variation for FooterLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: `FooterLinks`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterLinksSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<FooterLinksSliceDefaultPrimary>, Simplify<FooterLinksSliceDefaultItem>>;
/**
 * Slice variation for *FooterLinks*
 *
 */
type FooterLinksSliceVariation = FooterLinksSliceDefault;
/**
 * FooterLinks Shared Slice
 *
 * - **API ID**: `footer_links`
 * - **Description**: `FooterLinks`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterLinksSlice = prismicT.SharedSlice<"footer_links", FooterLinksSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { AboutUsDocumentData, AboutUsDocument, AutomationDocumentData, AutomationDocument, ContactsDocumentData, ContactsDocumentDataSlicesSlice, ContactsDocument, DesigningDocumentData, DesigningDocument, FooterDocumentData, FooterDocumentDataSlicesSlice, FooterDocument, GalleryDocumentData, GalleryDocument, HomeDocumentData, HomeDocument, ProductionDocumentData, ProductionDocument, RepairDocumentData, RepairDocument, AllDocumentTypes, ContactListSliceDefaultPrimary, ContactListSliceDefault, ContactListSliceVariation, ContactListSlice, FooterLinksSliceDefaultPrimary, FooterLinksSliceDefaultItem, FooterLinksSliceDefault, FooterLinksSliceVariation, FooterLinksSlice };
    }
}
