// Code generated by Slice Machine. DO NOT EDIT.

import ContactList from './ContactList';
import FooterLinks from './FooterLinks';

export {
	ContactList,
	FooterLinks,
};

export const components = {
	contact_list: ContactList,
	footer_links: FooterLinks,
};
