// Code generated by Slice Machine. DO NOT EDIT.

import AboutTemplate from './AboutTemplate';
import ContactList from './ContactList';
import FooterLinks from './FooterLinks';
import GalleryImages from './GalleryImages';
import GalleryItems from './GalleryItems';
import Headers from './Headers';
import ServicesItems from './ServicesItems';
import ServicesLayout from './ServicesLayout';

export {
	AboutTemplate,
	ContactList,
	FooterLinks,
	GalleryImages,
	GalleryItems,
	Headers,
	ServicesItems,
	ServicesLayout,
};

export const components = {
	about_template: AboutTemplate,
	contact_list: ContactList,
	footer_links: FooterLinks,
	gallery_images: GalleryImages,
	gallery_items: GalleryItems,
	headers: Headers,
	services_items: ServicesItems,
	services_layout: ServicesLayout,
};
